version: '3'

services:

  static:
    image: task:staticsImage
    build: 
      context: . 
      dockerfile: Dockerfile.static
    environment:
      - APP_PORT=8000
    ports:
      - 8000:8000
    restart: always
    #network_mode: host
    command: ./front-end/public/serve.py

  quotes:
    image: task:quotesImage
    build:
      context: .
      dockerfile: Dockerfile.quotes
    environment:
      - APP_PORT=8081
    ports:
      - 8081:8081
    restart: always


  newsfeed:
    image: task:newsfeedImage
    build:
      context: .
      dockerfile: Dockerfile.newsfeed
    environment:
      - APP_PORT=8082
    ports:
      - 8082:8082
    restart: always


  frontend:
    image: task:frontendImage
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - APP_PORT=8080
      - STATIC_URL=http://static:8000
      - QUOTE_SERVICE_URL=http://quotes:8081
      - NEWSFEED_SERVICE_URL=http://newsfeed:8082
    ports:
      - 8080:8080
    restart: always
