version: 2.1
jobs:

  build-frontend:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run:
          name: Build application
          command: |
            echo ${CIRCLE_WORKFLOW_ID:0:7}
            sudo apt-get install make
            make libs
            make clean all
            #make clean all
            #make test

  dockerizingq:
    docker:
      - image: circleci/golang:1.15
        #auth:
          #username: maliknabek
          #password:   # context / project UI env-var reference
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      
      # ... steps for building/testing app ...
     

      - setup_remote_docker:
          version: 19.03.13
          #docker_layer_caching: true

      # build and push Docker image
      - run: |
          #TAG=0.1.$CIRCLE_BUILD_NUM
          #docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
          #echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          #docker push CircleCI-Public/circleci-demo-docker:$TAG
          docker-compose build
          docker-compose up -d
          curl http://localhost:8001
          docker tag farid:java-leiningen-python3 maliknabek/myimage1:2.0
          echo "completed........."
          docker login -u maliknabek -p Italiawon7+++
          docker push maliknabek/myimage1:2.0 
          curl http://localhost:8001
workflows:
  default:
  
    jobs:
      
      - dockerizingq
          
      
